default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: prospector_sample_rails_app_development

test:
  <<: *default
  database: prospector_sample_rails_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
