# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f460991d3c6e1ed1ac781204e72af09789ac7ba5a23bd1e7fa5f039d8375b54a53285a958ef9fc0b5be501e338cbd7939008c6352f44f339f4454eaf6e778106

test:
  secret_key_base: 90416a826c6eb76cb5f25d4805910a92f6d15b559ccb811dcd9f04ce5162dff17d053e4013561d03996511a45c68ef0de24b114c2e3c75901f106e03de929ac9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
